### PR TITLE
Update app package.json

### PR DESCRIPTION
**Pull request by o-liver**
Same as https://github.com/SAP/cloud-samples-itelo/pull/1 as suggested by @avizov:
>Update package.json file with latest dependencies version:
>
>1. @sap/grunt-sapui5-bestpractice-build to version 1.3.64
>1. @sap/approuter to version 5.7.0
>1. Remove unneeded dev dependencies

### CODE REVIEW

**Comment by o-liver** [comment]
@chgeo @jonathanbaker7 This repo does not seem to be maintained and is not working properly. Maybe you want to mark it End of Life again?

**Comment by jonathanbaker7** [comment]
> @chgeo @jonathanbaker7 This repo does not seem to be maintained and is not working properly. Maybe you want to mark it End of Life again?

I don't work at SAP anymore, so you need to contact DevRel there.

**Comment by chgeo** [comment]
Hey.  Indeed, this repo is no longer maintained.  Thanks for reminding us to sunset it.  Will do so, and also close this PR.

**Comment by chgeo** [comment]
New sample code repo is https://github.com/SAP-samples/cloud-cap-samples/ (Node.js) and https://github.com/SAP-samples/cloud-cap-samples-java (Java)

**Pull request closed without merging**
